'use client'

import React from 'react'
import { CheckCircle2, Clipboard, FileCheck2, PenTool, RefreshCw, TriangleAlert } from 'lucide-react'
import './mf-workbench.css'

type Props={world:any;tick:number;actionable:Array<{id:string;name:string}>;logs:Array<{time:string;msg:string}>;onLog:(msg:string)=>void}

export function StepReport({world,tick,actionable,logs,onLog}:Props){
  const draftKey=`chapter_draft_${world?.id}`;const loadDraft=()=>{try{const raw=localStorage.getItem(draftKey);const d=raw?JSON.parse(raw):{};if(d.pov&&!actionable.some((e)=>e.id===d.pov))d.pov='';if(typeof d.tickFrom!=='number'||d.tickFrom<0)d.tickFrom=0;return d}catch{return{}}};const [tickFrom,setTickFrom]=React.useState(()=>loadDraft().tickFrom||0);const [pov,setPov]=React.useState(()=>loadDraft().pov||'');const [goal,setGoal]=React.useState(()=>loadDraft().goal||'');const [povOpen,setPovOpen]=React.useState(false)
  const [busy,setBusy]=React.useState(false);const [chapter,setChapter]=React.useState<any>(()=>loadDraft().chapter||null);const [run,setRun]=React.useState<any>(null);const [error,setError]=React.useState('');const [events,setEvents]=React.useState<any[]>([]);const [selectedEvents,setSelectedEvents]=React.useState<string[]>([]);const logRef=React.useRef<HTMLDivElement>(null);const pollRef=React.useRef<number|null>(null)
  React.useEffect(()=>{if(logRef.current)logRef.current.scrollTop=logRef.current.scrollHeight},[logs.length])
  React.useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify({chapter,tickFrom,pov,goal}))}catch{}},[draftKey,chapter,tickFrom,pov,goal])
  React.useEffect(()=>{if(!world?.id)return;void fetch(`/api/worlds/${world.id}/events?tickFrom=0`).then((r)=>r.ok?r.json():{events:[]}).then((d)=>setEvents(d.events||[])).catch(()=>setEvents([]))},[world?.id,tick])
  const stopPoll=()=>{if(pollRef.current){window.clearInterval(pollRef.current);pollRef.current=null}}
  const pollRun=async()=>{try{const r=await fetch(`/api/worlds/${world.id}/chapters`);const d=await r.json();if(!d.run)return false;setRun(d.run);if(d.run.status==='completed'&&d.chapter){setChapter(d.chapter);setBusy(false);stopPoll();onLog(`章节已落盘：${d.chapter.title}`);return true}if(d.run.status==='failed'){setError(d.run.error||'生成失败');setBusy(false);stopPoll();onLog(`成章失败：${d.run.error||'生成失败'}`);return true}}catch{}return false}
  React.useEffect(()=>{if(!world?.id)return;void (async()=>{try{const r=await fetch(`/api/worlds/${world.id}/chapters`);const d=await r.json();if(!d.run)return;setRun(d.run);if(d.run.status==='completed'&&d.chapter){setChapter(d.chapter);return}if(d.run.status==='running'||d.run.status==='queued'){setBusy(true);stopPoll();pollRef.current=window.setInterval(()=>{void pollRun()},2000)}}catch{}})();return stopPoll},[world?.id])
  const generate=async()=>{setBusy(true);setError('');setChapter(null);try{onLog(`正在组织 Tick ${tickFrom}–${tick} 的章节素材`);const response=await fetch(`/api/worlds/${world.id}/chapters`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tickFrom,tickTo:tick,eventIds:selectedEvents.length?selectedEvents:undefined,povEntityId:pov||undefined,goal:goal||undefined})});const value=await response.json();if(!response.ok)throw new Error(value.error||'生成失败');setRun(value.run);onLog(`任务已启动：${value.runId.slice(0,8)}`);stopPoll();pollRef.current=window.setInterval(()=>{void pollRun()},2000)}catch(cause){const message=cause instanceof Error?cause.message:String(cause);setError(message);setBusy(false);onLog(`成章失败：${message}`)}}
  const retry=async()=>{if(run?.tick==null)return;setBusy(true);setError('');try{const response=await fetch(`/api/worlds/${world.id}/tick/${run.tick}/retry-chapter`,{method:'POST'});const value=await response.json();if(!response.ok)throw new Error(value.error||'重试失败');setRun(value.run);stopPoll();pollRef.current=window.setInterval(()=>{void pollRun()},2000);onLog(`正在重试第 ${run.tick} 轮章节`)}catch(cause){setError(cause instanceof Error?cause.message:String(cause));setBusy(false)}}
  const issues:any[]=chapter?.validation?.issues||[]
  const dimensions:any[]=chapter?.validation?.dimensions||[]
  return <div className="mf-workbench workbench-panel"><div className="scroll-container">
    <div className="step-card active"><div className="card-header"><div className="step-info"><PenTool size={16}/><span className="step-title">章节编排</span></div><span className={`badge ${busy?'processing':'pending'}`}>{busy?'策划 · 写作 · 校验':'手动成章'}</span></div>
      <p className="api-note">CONTRACT → EVOLVE → DRAFT → 7D REVIEW → PUBLISH</p><p className="description">正式流程是一轮一章：事件先以待发布状态进入账本，正文通过七维审稿后 Tick 才发布。下方手动编排仅用于重组历史事件或创建新版本。</p>
      {run&&<div className={`auto-chapter-status ${run.status}`}><div><strong>{run.tick!=null?`Tick ${run.tick} · 自动章节`:'手动章节任务'}</strong><span>{run.message}</span></div><b>{run.status==='completed'?'已发布':run.status==='failed'?'已阻塞':`${run.progress}%`}</b></div>}
      <div style={{ border:'1px solid #E6E2DA', padding:12, marginBottom:12, background:'#FFF' }}><div style={{ display:'flex', justifyContent:'space-between', marginBottom:8 }}><strong>事件池</strong><small>{selectedEvents.length ? `已选 ${selectedEvents.length} 条` : '未选择则按 Tick 范围取材'}</small></div>{events.length===0?<span className="description">完成推演后，事件会出现在这里。</span>:<div style={{ display:'grid', gap:6, maxHeight:180, overflowY:'auto' }}>{events.slice(-20).reverse().map((event)=><label key={event.id} style={{ display:'flex', alignItems:'flex-start', gap:8, fontSize:12, cursor:'pointer' }}><input type="checkbox" checked={selectedEvents.includes(event.id)} onChange={(e)=>setSelectedEvents((current)=>e.target.checked?[...current,event.id]:current.filter((id)=>id!==event.id))}/><span><b>{event.summary||event.payload?.summary||event.type}</b><small style={{ display:'block', color:'#777' }}>Tick {event.tick} · {event.type}</small></span></label>)}</div>}</div>
      <div className="chapter-form"><label><span>起始 Tick</span><div className="tick-stepper"><button type="button" onClick={()=>setTickFrom((v:number)=>Math.max(0,v-1))} disabled={tickFrom<=0}>−</button><span className="tick-value">{tickFrom}<small> / {tick}</small></span><button type="button" onClick={()=>setTickFrom((v:number)=>Math.min(tick,v+1))} disabled={tickFrom>=tick}>+</button></div></label><label><span>限定视角</span><div className="pov-select"><button type="button" className="pov-button" onClick={()=>setPovOpen((o)=>!o)}><span>{actionable.find((e)=>e.id===pov)?.name||'由章节引擎选择'}</span><span className="pov-arrow">▾</span></button>{povOpen&&<><div className="pov-backdrop" onClick={()=>setPovOpen(false)}/><div className="pov-popup"><button type="button" className={`pov-option${!pov?' selected':''}`} onClick={()=>{setPov('');setPovOpen(false)}}>由章节引擎选择</button>{actionable.map((entity)=><button type="button" key={entity.id} className={`pov-option${pov===entity.id?' selected':''}`} onClick={()=>{setPov(entity.id);setPovOpen(false)}}><span>{entity.name}</span></button>)}</div></>}</div></label><label className="goal-field"><span>本章目标 <small>可选</small></span><input value={goal} onChange={(event)=>setGoal(event.target.value)} placeholder="例如：让读者发现每次战斗后偶像都会陷入丑闻"/></label><button className="action-btn" disabled={busy||tick<tickFrom||!world?.visibilityConfirmed} onClick={generate}>{busy?'正在经过五步写作流程……':`生成 Tick ${tickFrom}–${tick} 章节`}</button></div>
      {busy&&run&&<div className="run-stages">{[['queued','等待'],['material','素材准备'],['outline','章节大纲'],['draft','正文写作'],['validate','逻辑校验'],['revise','修订'],['saving','落盘']].map(([key,label])=>{const order=['queued','material','outline','draft','validate','revise','saving','completed'];const done=order.indexOf(run.stage)>order.indexOf(key)||run.stage==='completed';const active=run.stage===key;return <span key={key} className={`run-stage${done?' done':''}${active?' active':''}`}>{done?'✓ ':''}{label}{active?` · ${run.progress}%`:''}</span>})}<span className="run-msg">{run.message}</span></div>}
      {error&&<div className="chapter-alert error" role="alert"><TriangleAlert size={15}/><span><strong>章节未通过，下一轮已锁定</strong>{error}</span>{run?.status==='failed'&&run?.tick!=null&&<button className="retry-chapter" onClick={retry} disabled={busy}><RefreshCw size={13}/>按原契约重试</button>}</div>}
    </div>
    <div className="step-card"><div className="card-header"><div className="step-info"><FileCheck2 size={16}/><span className="step-title">逻辑校验</span></div>{chapter&&<span className={`badge ${chapter.validation?.passed?'success':'processing'}`}>{chapter.validation?.passed?'通过':'已修订'}</span>}</div>
      {!chapter?<p className="description">章节生成后，这里会展示设定、人物、节奏、因果、伏笔、钩子与审美七个维度。任一低于 70、平均低于 80 或存在 critical/error 都不能发布。</p>:<><div className="review-dimensions">{dimensions.map((dimension)=><div key={dimension.key}><span>{dimensionLabel(dimension.key)}</span><strong className={dimension.score<70?'low':''}>{Math.round(dimension.score)}</strong><small>{dimension.evidence}</small></div>)}</div>{issues.length===0?<div className="chapter-alert success"><CheckCircle2 size={16}/><span><strong>七维审稿通过</strong>平均 {Math.round(chapter.validation?.averageScore||0)} 分；删除测试：{chapter.validation?.deletionTestPassed?'通过':'未记录'}。</span></div>:<div className="validation-list">{issues.map((issue,index)=><div key={index}><TriangleAlert size={14}/><span><strong>{issue.severity==='critical'?'致命':issue.severity==='error'?'错误':'提醒'}</strong>{issue.message}{issue.quote&&<small>“{issue.quote}” · {issue.contractField}</small>}</span></div>)}</div>}</>}
    </div>
    <div className="step-card chapter-output"><div className="card-header"><div className="step-info"><span className="step-num">MD</span><span className="step-title">{chapter?.title||'正文预览'}</span></div>{chapter&&<><button className="copy-chapter" onClick={()=>void navigator.clipboard.writeText(chapter.markdown)}><Clipboard size={13}/>复制 Markdown</button><button className="copy-chapter" onClick={()=>{const blob=new Blob([chapter.markdown],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${chapter.title}.txt`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}}>导出 TXT</button></>}</div>{chapter?<article>{chapter.markdown}</article>:<div className="chapter-placeholder">章节文件将按作品独立保存，可以后续重新生成和恢复版本。</div>}</div>
  </div><div className="system-logs"><div className="log-header"><span>WRITING PIPELINE</span><span>{world?.id?.slice(0,8)||'NO_WORLD'}</span></div><div className="log-content" ref={logRef}>{logs.map((log,index)=><div className="log-line" key={index}><span className="log-time">{log.time}</span><span className="log-msg">{log.msg}</span></div>)}</div></div></div>
}
function dimensionLabel(value:string){return({world_consistency:'设定一致',character_consistency:'人物一致',pacing_density:'节奏密度',causal_coherence:'场景因果',foreshadow_health:'伏笔健康',hook_quality:'章末钩子',aesthetic_quality:'审美去AI'} as Record<string,string>)[value]||value}
